version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=rootpassword1!
  authentication:
    build: './authentication'
    ports:
      - "8080:8080"
    depends_on:
      - db
